/**
 * @packageDocumentation
 * @module api.functional.aa
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { aa } from "../../../app.controller";

/**
 * @controller AppController.getHello
 * @path GET /aa
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
  connection: IConnection,
): Promise<getHello.Output> {
  return !!connection.simulate
    ? getHello.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...getHello.METADATA,
        path: getHello.path(),
      });
}
export namespace getHello {
  export type Output = Primitive<aa>;

  export const METADATA = {
    method: "GET",
    path: "/aa",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/aa";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<aa>> => typia.random<Primitive<aa>>(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
